### PR TITLE
Unit tests for all components

### PR DESCRIPTION
**Pull request by vpulim**
This PR adds unit tests for all components.

- [x] logging
- [x] blockchain
- [x] handler
- [x] net/peer
- [x] net/peerpool
- [x] net/protocol
- [x] net/server
- [x] rpc
- [x] service
- [x] sync
- [x] util
- [x] node

### CODE REVIEW

**Comment by holgerd77** [comment]
Whew, list completion makes some good progress. 👍 Out of interest: did you find (significant) bugs along the way? Or is everything just working as intended?

**Comment by vpulim** [comment]
@holgerd77 Just a few bugs... nothing major. Here are some examples:

1. Block incorrectly wrapped in a Promise: https://github.com/ethereumjs/ethereumjs-client/pull/70/files#diff-939c5cdcb48ce94b997a3d8b68a04b61L90
2. Another incorrectly wrapping in a Promise: https://github.com/ethereumjs/ethereumjs-client/pull/70/files#diff-ea1cea58e6f009f5587836522e31cb9fL58
3. Wrong default value: https://github.com/ethereumjs/ethereumjs-client/pull/70/files#diff-ef6d31d2252057eea76e75a9a56715eeL16
4. Missing reject value: https://github.com/ethereumjs/ethereumjs-client/pull/70/files#diff-b131dd2a34954a13576e8d0bf8267c99L204

I think ``TypeScript`` would have helped catch most of these cases

**Comment by holgerd77** [comment]
Just out of interest, no need to change here on the last stages: why are you doing this in such a monster 🐲 PR and not adding test types PR by PR? Does this have advantages regarding working out utility functions or something?

**Comment by vpulim** [comment]
No real advantages. Just wanted to avoid polluting the commit history. Also, I underestimated the amount of work 😂

**Comment by holgerd77** [comment]
Hehe. 😛

**Comment by holgerd77** [comment]
Whew. A whopping > 2.000 lines of code added. Not in all cases of software dev a sign for quality, but in this case really impressive! 👍

**Comment by vpulim** [comment]
😅Thanks @holgerd77. Not sure if it was worth it, but I did catch a few bugs and hopefully will identify any future bugs/typos. Now, on to integration tests! These should be more useful I think.

**Comment by holgerd77** [comment]
Think so too, this gives a very solid foundation and will likely pay off in the future! 😄

**Pull request merged**
