### PR TITLE
adding rpc method eth_getBlockByHash

### PR DESCRIPTION
**Pull request by bit-warrior**
Added  eth_getBlockByHash to rpc methods.
Had to change  lib/blockchain/chain.js to inject dummy blockchain for testing.

### CODE REVIEW

**Comment by vpulim** [comment]
@bit-warrior Thanks for submitting this PR. I was confused as to why you added a new getBlockByHash() method since the existing getBlock() method also looks up blocks by hash (in addition to looking up blocks by number). Was there another reason that I missed?

**Comment by bit-warrior** [comment]
@vpulim  i  missed to see that. thanks for your input. I will make the changes and resubmit.

**Comment by bit-warrior** [comment]
@vpulim update same pull request with changes as you suggested.

**Comment by vpulim** [comment]
@bit-warrior Looks great! Do you think you can squash your commits into a single commit and then I'll merge? Thanks

**Comment by bit-warrior** [comment]
@vpulim squashed the commits into one. thanks

**Comment by vpulim** [comment]
It looks like like you merged your changes into the latest commit on the master branch (3a07792 - Merge pull request #43 from ethereumjs/blockchain-api...) instead of squashing your commits into a new commit that comes after that one.

If you can, please undo that and create a new commit that only contains your changes. If you do it properly, the commit log on your local rpc-apis branch should look something like this:

```
commit xxxxxxx
Author: bit-warior
Date:   Fri Aug 10 00:00:00 2018 -0000

    Added rpc method eth_getBlockByHash**

commit 3a07792ffc2be13fee6e891d23074ef68c58e075
Merge: 7d4926b b17971f
Author: Vinay Pulim <vpulim@users.noreply.github.com>
Date:   Fri Aug 3 08:33:15 2018 -0400

    Merge pull request #43 from ethereumjs/blockchain-api

    Modified Chain class methods to match etheremjs-blockchain and fix RPC bugs

commit b17971fed43224c28cf9fdfe350613fb0f5b5b7d
Author: Vinay Pulim <v@pulim.com>
Date:   Fri Aug 3 07:42:32 2018 -0400

    Modified Chain class methods to match etheremjs-blockchain. Fix RPC bugs.

(continued...)
```

The first commit is your squashed commit and the rest are existing commits on master.

**Comment by bit-warrior** [comment]
@vpulim reverted back the merge and committed on top of it. Not sure though if there any alternate way to do it.

**Comment by vpulim** [comment]
@bit-warrior Type in the following commands exactly as shown:

```
cd /tmp
git clone git@github.com:Avarch-org/ethereumjs-client.git
cd ethereumjs-client
git checkout rpc-apis
git reset --soft master
git commit -m 'Added rpc method eth_getBlockByHash'
git push --force origin rpc-apis
```

**Comment by bit-warrior** [comment]
Thanks @vpulim , now i can see going as one commit

**Comment by vpulim** [comment]
@bit-warrior Great! We're almost there... it looks like there is an EventEmitter memory leak error that is preventing the tests from running. If you make the following change to ``test/rpc/helpers.js``, it should fix the problem.

```
 const Manager = require('../../lib/rpc')
 const Logger = require('../../lib/logging')

+const config = { loglevel: 'error' }
+config.logger = Logger.getLogger(config)
+
 module.exports = {
   startRPC (methods, port = 3000) {
     const server = jayson.server(methods)
@@ -16,8 +19,6 @@ module.exports = {
   },

   createManager (node) {
-    const config = { loglevel: 'error' }
-    config.logger = Logger.getLogger(config)
     return new Manager(node, config)
   }
 }
```

After you make the change, amend the commit and force push again:

```
git commit --amend -am 'Added rpc method eth_getBlockByHash'
git push --force origin rpc-apis
```

**Comment by bit-warrior** [comment]
I made changes in local..............
const jayson = require('jayson')

const Manager = require('../../lib/rpc')
const Logger = require('../../lib/logging')

const config = { loglevel: 'error' }
config.logger = Logger.getLogger(config)

module.exports = {
  startRPC (methods, port = 3000) {
    const server = jayson.server(methods)
    const httpServer = server.http()
    httpServer.listen(port)
    return httpServer
  },

  closeRPC (server) {
    server.close()
  },

  createManager (node) {
    return new Manager(node, config)
  }
}


but still many test cases are failing........

const jayson = require('jayson')

const Manager = require('../../lib/rpc')
const Logger = require('../../lib/logging')

const config = { loglevel: 'error' }
config.logger = Logger.getLogger(config)

module.exports = {
  startRPC (methods, port = 3000) {
    const server = jayson.server(methods)
    const httpServer = server.http()
    httpServer.listen(port)
    return httpServer
  },

  closeRPC (server) {
    server.close()
  },

  createManager (node) {
    return new Manager(node, config)
  }
}

**Comment by bit-warrior** [comment]
const jayson = require('jayson')

const Manager = require('../../lib/rpc')
const Logger = require('../../lib/logging')

const config = { loglevel: 'error' }
config.logger = Logger.getLogger(config)

module.exports = {
  startRPC (methods, port = 3000) {
    const server = jayson.server(methods)
    const httpServer = server.http()
    httpServer.listen(port)
    return httpServer
  },

  closeRPC (server) {
    server.close()
  },

  createManager (node) {
    return new Manager(node, config)
  }
}const jayson = require('jayson')

const Manager = require('../../lib/rpc')
const Logger = require('../../lib/logging')

const config = { loglevel: 'error' }
config.logger = Logger.getLogger(config)

module.exports = {
  startRPC (methods, port = 3000) {
    const server = jayson.server(methods)
    const httpServer = server.http()
    httpServer.listen(port)
    return httpServer
  },

  closeRPC (server) {
    server.close()
  },

  createManager (node) {
    return new Manager(node, config)
  }
}



this is how it looks like now, but still many test cases are failing..

1..36
# tests 36
# pass  20
# fail  16

**Comment by bit-warrior** [comment]
const Manager = require('../../lib/rpc')
const Logger = require('../../lib/logging')

const config = { loglevel: 'error' }
config.logger = Logger.getLogger(config)

module.exports = {
startRPC (methods, port = 3000) {
const server = jayson.server(methods)
const httpServer = server.http()
httpServer.listen(port)
return httpServer
},

closeRPC (server) {
server.close()
},

createManager (node) {
return new Manager(node, config)
}
}

this is how it looks like now, but still many test cases are failing..

1..36
tests 36
pass 20
fail 16

**Comment by bit-warrior** [comment]
failing at  , trying to understand why 
 st.ok(chain.opened, 'chain should open if getBlocks() called')

(node:8314) UnhandledPromiseRejectionWarning: ReadError: Database is not open
    at maybeError (/tmp/ethereumjs-client/node_modules/levelup/lib/levelup.js:165:23)
    at LevelUP.get (/tmp/ethereumjs-client/node_modules/levelup/lib/levelup.js:184:7)
    at Blockchain._numberToHash (/tmp/ethereumjs-client/node_modules/ethereumjs-blockchain/index.js:916:11)
    at async.waterfall (/tmp/ethereumjs-client/node_modules/ethereumjs-blockchain/index.js:429:14)
    at nextTask (/tmp/ethereumjs-client/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/tmp/ethereumjs-client/node_modules/async/dist/async.js:5334:5)

**Comment by bit-warrior** [comment]
wrapping in try catch blocking is fixing the error and all the test cases are passing

test/rpc/chain,js

let me know if you want to make the chnages and commit.

 try {
      await chain.getBlocks(block.hash())

      st.ok(chain.opened, 'chain should open if getBlocks() called')
      await chain.close()
      await chain.getBlock(block.hash())
      st.ok(chain.opened, 'chain should open if getBlock() called')

      await chain.close()
      await chain.getLatestHeader()
      st.ok(chain.opened, 'chain should open if getLatestHeader() called')
      await chain.close()
      await chain.getLatestBlock()
      st.ok(chain.opened, 'chain should open if getLatestBlock() called')
      await chain.close()
      await chain.getTd(block.hash())
      st.ok(chain.opened, 'chain should open if getTd() called')
      st.equal(await chain.open(), false, 'skip open if already opened')
    } catch (err) {
    
    }

**Comment by vpulim** [comment]
@bit-warrior I'm not seeing that error. Can you try committing without the try/catch wrapper? I'm curious if its local to your environment or if it also occurs in circle ci. We should figure out why the exception is being thrown rather than hiding it with the try/catch.

**Comment by bit-warrior** [comment]
can you also comfirm changes below looks good on helper.js before i push it. Although i did not understand event emitter memory leak part. if possible can you tell me more abt it.

On a different note, what editor and tools are you using for debugging and coding to increase efficiency. 

const jayson = require('jayson')

const Manager = require('../../lib/rpc')
const Logger = require('../../lib/logging')

const config = { loglevel: 'error' }
config.logger = Logger.getLogger(config)
module.exports = {
  startRPC (methods, port = 3000) {
    const server = jayson.server(methods)
    const httpServer = server.http()
    httpServer.listen(port)
    return httpServer
  },

  closeRPC (server) {
    server.close()
  },

  createManager (node) {
    return new Manager(node, config)
  }
}

**Comment by vpulim** [comment]
@bit-warrior Those changes to helper.js look good. Go ahead and amend your existing commit and force push it.

Regarding the memory leak: Each time a new logger is created, it creates a listener for the uncaughtException event which Node.js throws whenever an exception isn't caught by a try/catch. Before we fixed it, ``createManager()`` was creating a new logger each time it was called, thus creating many listeners for the uncaughtException event. By default, Node.js only allows 10 listeners to be registered for any event and we were going over that limit. By moving the ``Logger.getLogger()`` call outside of the ``createManager()`` function, we only create one instance of the logger and thus only register one listener for the uncaughtException event.

The only tool I use is Atom for editing files. I usually debug by inserting ``console.log()`` or ``logger.debug()`` calls throughout my code. But for more tricky bugs, I will use Chrome DevTools: https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by bit-warrior** [comment]
Thansk for explaining the memory leak. I have pushed the changes

**Pull request merged**
