### PR TITLE
Update libp2p defaults

### PR DESCRIPTION
**Pull request by vpulim**
- Update default libp2p options

### CODE REVIEW

**Comment by holgerd77** [comment]
If you've got some time, could you head over at 16:35 to the end of devp2p session in Prism room (would have to be in time)? Would like to introduce you to Felix and have some short libp2p exchange.

**Comment by vpulim** [comment]
@holgerd77 sorry, I left the conference hall and am back at hotel to finish up packing and finish some outstanding client github tasks. I can come back after an hour if Felix is still there?

**Comment by holgerd77** [comment]
Ah no, nevermind. Will you have time for a last meetup (beer? :-)) and when? Or do you have to head directly to the airport?

**Comment by vpulim** [comment]
Replied on gitter. Heading back to conference center at 17:30 to meet up

**Pull request merged**
