### PR TITLE
Override implicit dependency lint rule for tests

### PR DESCRIPTION
**Pull request by rumkin**
Add overrides to eslint rules to fix false-positive checks in tests directory. It allows to require dev-dependencies from `test/` directory.

### Questions

- [ ] This PR probably requires changes in tests to remove eslint-disable comments. But it seems conflict-prone to change whole tests files at once. And it seems logical to fix it continuously. Is `.eslint.js` changes is enough for this?

- [ ] Should it be done organisation-wide in [eslint-config-defaults](https://github.com/ethereumjs/ethereumjs-config/tree/master/packages/lint)?

### CODE REVIEW

**Comment by ryanio** [comment]
lgtm, yes I'd say we can PR to add this to eslint-config-defaults if others agree 👍

**Comment by cgewecke** [comment]
lgtm as well and +1 on adding to eslint-config-defaults.

**Review by holgerd77 — APPROVED** [review]
LGTM

**Comment by holgerd77** [comment]
(don't be intimidated here, normally one review is totally enough 😜 )

**Pull request merged**
