### PR TITLE
Adding RPC method protocolVersion

### PR DESCRIPTION
**Pull request by bit-warrior**

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi @bit-warrior, great that you are taking on this! Your PR have fallen into a period with a huge structural rewrite under way, which I just merged: https://github.com/ethereumjs/ethereumjs-client/pull/37

Since your PR is setting up some structures which got obsolete with the new framework, I decided to first merge the framework PR, otherwise too much of this would have to be changed again. Could you do an adopted PR (probably a new-one) on top of this? (sorry, but it just made more sense this way around, hope you nevertheless stay on board! 😄 )

Some first review of your PR: it should generally be avoided to hard-code constants somewhere in the library, like in your case the protocol version. This should be read dynamically from the peer managing or network classes, please have a closer look into the new structure from @vpulim for this.

**Comment by bit-warrior** [comment]
Sure i will resubmit the PR with the recommended  changes. @vpulim proposed structure looks much cleaner.

**Comment by vpulim** [comment]
@bit-warrior I would recommend modifying the ``RPCManager`` constructor to take ``node`` as a parameter instead of ``chain`` (as well as making a corresponding change to the constructor for the ``Eth`` module (``rpc/modules/eth.js``). This way you can access the protocol version using code similar to the following:

```
const ethService = node.services.find(s => s instanceof EthService)
const ethProtocol = ethService.protocols().find(p => p. name === 'eth')
const versions = ethProtocol.versions
```

**Comment by bit-warrior** [comment]
Thanks Vinay. Above code will return an array of supported protocols [62,63].  Geth return  "63" ,not sure whats the algorithm to decide protocolversion.

**Comment by vpulim** [comment]
@bit-warrior I would just return the largest version in the list:

```
Math.max(...versions)
```

**Comment by vpulim** [comment]
@bit-warrior I closed #40 since the changes you need are now part of #41. I'll merge tomorrow if I don't get any feedback by then.

**Comment by bit-warrior** [comment]
cancelled

**Pull request closed without merging**
