### PR TITLE
fix: add pyenv version file

### PR DESCRIPTION
**Pull request by BelfordZ**

### CODE REVIEW

**Comment by holgerd77** [comment]
Can you describe what this fixes?

I am actually not aware that Python is needed for any parts of the library? Am I missing something?

**Comment by BelfordZ** [comment]
I was unable to npm install without explicitly using python 2

**Comment by BelfordZ** [comment]
While we are talking about it, you may want to consider adding a .node-version file as well, cause this wont run under node 10 atm.

**Comment by vpulim** [comment]
@BelfordZ Since node-gyp doesn't support python 3, you might be better off running ``npm config set python /path/to/executable/python2.7``. This should prevent ``npm install`` errors on not just ``ethereumjs-client`` but any other nodejs libraries that could potential generate node-gyp errors due to an incorrect python version.

Also, I'm not having any issues running under node 10. Can you provide more details about your environment? I would recommend install ``nvm`` and use that to switch tp node 10. Also, make sure you delete the ``node_modules`` directory and the ``package-lock.json`` file before you ``npm install`` under node 10.

**Comment by BelfordZ** [comment]
using `nodeenv` on `10.11.0`. Ill paste the output another time, not on the right computer atm.

While I agree, node-gyp still not support python 3 is for sure the problem here, but as a matter of making it an easy upstart, pyenv is a very common tool for python users, and having a file to explicitly require python2, be it for node-gyp or not, could help reduce some friction for people. Certainly would have for me :).

**Comment by BelfordZ** [comment]
Feel free to close this PR if you don't think it suits the project :)

**Comment by vpulim** [comment]
@BelfordZ I'm going back and forth on this. On one hand, it would make ``npm install`` more seamless for those developers that have python3 as their default. On the other hand, its adding more dot file clutter to the project. Plus, npm clearly explains how to address the issue (``You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0``)

I'll leave this issue open for now so others can chime in with their opinions (@holgerd77? 😄 )

**Comment by holgerd77** [comment]
I also have a tendency to find it too much "around the corner" to add such version files here TBH.

**Comment by vpulim** [comment]
Sounds good. Thanks for the suggestion @BelfordZ and hopefully this doesn't dissuade you from further contributions. I'm going to close this out.

**Pull request closed without merging**
